src/cart/urls.py
from django.urls import path
from cart.views import AddBookToCart, CartDelete, CartDetail
from . import views
app_name = 'cart'

urlpatterns = [
    path('add_to_cart/', views.AddBookToCart.as_view(), name='add'),
    path('delete_cart/<int:pk>', views.CartDelete.as_view(), name='delete'),
    path('detail_cart', views.CartDetail.as_view(), name='detail'),
] 

src/order/urls.py
from django.urls import path
from order.views import DetailOrder, DeleteOrder, OrderDone, OrderBy, OrderFor
app_name="order"

urlpatterns = [
    path('books_in_order/', OrderBy.as_view(), name='books_in_order'),
    path('detail_order/', DetailOrder.as_view(), name='detail'),
    path('delete/<int:pk>', DeleteOrder.as_view(), name='delete'),
    path('order_done/', OrderDone.as_view(), name='order_done'),
    path('order_for_user/', OrderFor.as_view(), name='order_for_user'),

]

src/profiles/urls.py
from django.urls import path
from profiles.views import CreateProfile, UpdateProfile, DeleteProfile, DetailProfile, Login, LoginDone, Logout, PasswordChange, PasswordChangeDone
from . import views
app_name = 'profile'

urlpatterns = [
    path('update_profile/<int:pk>', UpdateProfile.as_view(), name='update'),
    path('delete_profile/<int:pk>', DeleteProfile.as_view(), name='delete'),
    path('detail_profile/<int:pk>', DetailProfile.as_view(), name='detail'),
    path('create_profile/', CreateProfile.as_view(), name='create'),
    path('login/', Login.as_view(), name='login'),
    path('login_done/', LoginDone.as_view(), name='login_done'),
    path('logout/', Logout.as_view(), name='logout'),
    path('password_change/', PasswordChange.as_view(), name='password_change'),
    path('password_change_done/', PasswordChangeDone.as_view(), name='password_change_done'),
] 

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import HomePageView, Search

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('genres/', include('genre.urls', namespace='genres')),
    path('books/', include('books.urls', namespace='books')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('author/', include('author.urls', namespace='author')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('publisher/', include('publisher.urls', namespace='publisher')),
    path('series/', include('series.urls', namespace='series')),
    path('', HomePageView.as_view(), name='home'),
    path('search/', Search.as_view(), name='search')
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse_lazy

User = get_user_model()

class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    username = models.CharField(
        verbose_name='Имя пользователя',
        max_length=15
    )
    password = models.CharField(
        verbose_name='Пароль',
        max_length=15
    )
    first_name = models.CharField(
        verbose_name='Имя',
        max_length=50
    )
    last_name = models.CharField(
        verbose_name='Фамилия',
        max_length=50
    )
    email = models.EmailField(verbose_name='E-mail')
    phone_number = models.IntegerField(verbose_name='Номер телефона')
    address1 = models.CharField(
        verbose_name='Адрес доставки основной',
        max_length=500
    )
    address2 = models.CharField(
        verbose_name='Адрес доставки дополнительный',
        max_length=500,
        null=True,
        blank=True
    )
    image = models.ImageField(
        verbose_name='Изображение',
        upload_to='profile_image',
        null=True,
        blank=True
    )

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

    def get_absolute_url(self):
        return reverse_lazy("home")

src/profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class CreateProfileForm(forms.Form):
    username = forms.CharField(label='Имя пользователя', max_length=15)
    password = forms.CharField(label='Пароль', max_length=15)
    password1 = forms.CharField(label='Повторите пароль', max_length=15)
    first_name = forms.CharField(label='Имя', max_length=50)
    last_name = forms.CharField(label='Фамилия', max_length=50)
    email = forms.EmailField(label='Email')
    phone_number = forms.IntegerField(label='Номер телефона')
    address1 = forms.CharField(label='Адрес доставки основной', max_length=500)
    address2 = forms.CharField(label='Адрес доставки дополнительный', max_length=500)
    image = forms.ImageField(label='Изображение')

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
        'first_name',
        'last_name',
        'phone_number',
        'email',
        'image'
        )

src/profiles/views.py
from .models import Profile, User
from books.models import Books
from genre.models import Genre
from author.models import Author
from django.template import Context
# from cart.models import BooksInCart
from .forms import CreateProfileForm, UpdateProfileForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, authenticate
from django.contrib.contenttypes.models import ContentType 
from django.contrib.auth.models import Permission, Group
from django import forms
from django.http import HttpResponseRedirect
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.views.generic import FormView, UpdateView, DetailView, DeleteView, TemplateView

class CreateProfile(FormView):
    form_class = CreateProfileForm
    template_name = 'profiles/create_profile.html'

    def form_valid(self, form):
        form_username = form.cleaned_data['username']
        form_password = form.cleaned_data['password']
        form_first_name = form.cleaned_data['first_name']
        form_last_name = form.cleaned_data['last_name']
        form_email = form.cleaned_data['email']
        form_phone_number = form.cleaned_data['phone_number']
        form_address1 = form.cleaned_data['address1']
        form_address2 = form.cleaned_data['address2']
        form_image = form.cleaned_data['image']
        
        if form.cleaned_data['password'] != form.cleaned_data['password1']:
            raise forms.ValidationError ("Пароли не совпадают")

        user, create=User.objects.get_or_create(
            username=form_username,
            password=form_password,
            first_name=form_first_name,
            last_name=form_last_name,
            email=form_email
        )
        user.groups.add(Group.objects.get(name='Customers'))
        if create:
            user.set_password(form_password)
            user.save()
        profile, create = Profile.objects.get_or_create(
            user=User.objects.get(username=form_username),
            first_name=form_first_name,
            last_name=form_last_name,
            email=form_email,
            phone_number=form_phone_number,
            address1=form_address1,
            address2=form_address2,
            image=form_image
        )
        if user.is_anonymous:
            user = None

        return HttpResponseRedirect(self.get_success_url())
        
    def get_success_url(self):
        return reverse_lazy('profiles:login_done')

class UpdateProfile(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = UpdateProfileForm
    template_name = 'profiles/update_profile.html'
    
    def get_success_url(self):
        return reverse_lazy('profile:detail', kwargs={'pk': self.object.pk})

class DeleteProfile(LoginRequiredMixin, DeleteView):
    model = Profile
    template_name = 'profiles/delete_profile.html'
    success_url = reverse_lazy('home')

class DetailProfile(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'profiles/detail_profile.html'

# ЛОГИН
class Login(LoginView):
    template_name = 'profiles/login.html'
    
    def get_success_url(self):
       return reverse_lazy('home')

class LoginDone(TemplateView):
    template_name = 'profiles/login_done.html'

class Logout(LogoutView):
    template_name = 'profiles/logout.html'

    def get_success_url(self):
       return reverse_lazy('home')

class PasswordChange(PasswordChangeView):
    template_name = 'profiles/password_change.html'

    def get_success_url(self):
       return reverse_lazy('profiles:password_change_done')

class PasswordChangeDone(PasswordChangeDoneView):
    template_name = 'profiles/password_change_done.html'

    def get_success_url(self):
       return reverse_lazy('home')

src/profiles/templates/profiles/create_profile.html
{% extends 'base_login.html' %}
{% load crispy_forms_tags %}

{% block title %}Добавление пользователя{% endblock title %}

{% block body %}
  <div class='container'>
      <br><br>
      <h1>Добавить пользователя</h1>
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
          {{ form|crispy }}
          <button type="submit" class="btn btn-outline-danger">Сохранить</button>
        </div>
      </form>
  </div>  
{% endblock body %}

src/profiles/templates/profiles/delete_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Удаление пользователя{% endblock title %}

{% block body %}
    <div class='container'>
        <br><br>
        <h1>Удалить пользователя {{ object.name }}</h1>
        <form action="" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger">Вы уверены?</button>
        </form>
    </div>  
{% endblock body %}

src/profiles/templates/profiles/detail_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Информация о пользователе{% endblock title %}

{% block body %}
    <div class='container'>
        <a href="{% url "profile:password_change" %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Изменить пароль</a><br>
        <br>
        <a href="{% url "profile:update" object.pk %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Изменить данные пользователя</a><br>
        <br>
        
        <h1>Пользователь {{ object.first_name }} {{ object.last_name }}</h1>
        <div class='container'>
        <br><br>
        <table width='100%' class='container' class="table table-bordered" cellspacing="0" border="2">
            <tr>
                <th scope="col">Изображение</th><td><img src="{{ profile.image.url }}" width="150" alt=""></td>
            </tr>
            <tr>
                <th scope="col">Никнэйм</th><td>{{ object.user.username }}</td>
            </tr>
            <tr>
                <th scope="col">Имя</th><td>{{ object.first_name }}</td>
            </tr>
            <tr>
                <th scope="col">Фамилия<td>{{ object.last_name }}</td>
            </tr>
            <tr>
                <th scope="col">Email</th><td>{{ object.user.email }}</td>
            </tr>
            <tr>
                <th scope="col">Номер телефона</th><td>{{ profile.phone_number }}</td>
            </tr>
            <tr>
                <th scope="col">Адрес доставки основной</th><td>{{ profile.address1 }}</td>
            </tr>
            <tr>
                <th scope="col">Адрес доставки дополнительный</th><td>{{ profile.address2 }}</td>
            </tr>
        </table><br>
        <a href="{% url "order:order_for_user"%}?user_pk={{ user.pk }}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Заказы пользователя</a><br>
        <br>
    </div>  
     
{% endblock body %}

src/profiles/templates/profiles/login.html
{% extends 'base_login.html' %}
{% load crispy_forms_tags %}

{% block title %}Логин{% endblock title %}

{% block body %}
  <div class='container'>
      <br><br><br>

{% if form.errors %}
<p>Ваши логин и пароль не совпадают. Попробуйте еще раз.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>У Вас нет доступа к этой странице.</p>
    {% else %}
    <p>Пожалуйста, войдите в учетную запись для продолжения.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'auth:login' %}">
{% csrf_token %}
    <div>
      <div class="form-group">
        <label for="{{ object.username }}">Имя пользователя</label>
        <input type="username" class="form-control" id="{{ object.username }}" aria-describedby="Help">
        <small id="Help" class="form-text text-muted">Введите имя пользователя</small>
      </div>
      <div class="form-group">
        <label for="{{ object.password }}">Пароль</label>
        <input type="password" class="form-control" id="{{ object.password }}">
      </div>
      <button type="submit" class="btn btn-primary">Войти</button>
    </div>
      <button type="submit" class="btn btn-danger"><a href="{% url "profile:create" %}">Зарегистрироваться</a></button><br>

</form>

<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
{% comment %} <p><a href="{% url 'password_reset' %}">Lost password?</a></p> {% endcomment %}

{% endblock %}

src/profiles/templates/profiles/login_done.html
{% extends "base.html" %}

{% block title %}Добро пожаловать{% endblock %}

{% block body %}
    <div class="container"> 
        <h1>Добро пожаловать!</h1>
        <p>Ваша учетная запись успешно сохранена. Теперь Вы можете <a href="{% url "profile:login" %}">войти</a>.</p>
    </div>
{% endblock %}

src/profiles/templates/profiles/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}Список книг{% endblock title %}

{% block body %}
 <div class='container'>
    <h1>Выход</h1>
        <p>Вы успешно вышли из учетной записи. Вы можете <a href="{% url "profiles:login" %}">войти снова</a>.</p>
 </div>
{% endblock body %}

src/profiles/templates/profiles/password_change.html
{% extends 'base_login.html' %}
{% load crispy_forms_tags %}

{% block title %}Изменение пароля{% endblock title %}

{% block body %}
   <div class='container'>
    <h1>Изменение пароля</h1>
    <p>Заполните данные для изменения пароля.</p>
    <form action="." method="post">
        {{ form|crispy }}
        <p><input type="submit" value="Поменять"></p>
        {% csrf_token %}
    </form>
    </div>
{% endblock %}

src/profiles/templates/profiles/password_change_done.html
{% extends 'base_login.html' %}
{% load crispy_forms_tags %}

{% block title %}Изменение пароля{% endblock title %}

{% block body %}
 <h1>Пароль изменен</h1>
    <p>Ваш пароль успешно изменен.</p>

{% endblock body %}

src/profiles/templates/profiles/update_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Изменение пользователя{% endblock title %}

{% block body %}
    <div class='container'>
    <br><br>
    <h1>Изменить данные пользователя</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Подтвердить">
    </form>
    </div> 
{% endblock body %}