src/books/urls.py
from django.urls import path
from books.views import CreateBook, UpdateBook, ListBook, DeleteBook, DetailBook, HomePageView
from . import views
app_name = 'books'

urlpatterns = [
    path('create_book/', views.CreateBook.as_view(), name='create'),
    path('update_book/<int:pk>', views.UpdateBook.as_view(), name='update'),
    path('list_book/', views.ListBook.as_view(), name='list'),
    path('delete_book/<int:pk>', views.DeleteBook.as_view(), name='delete'),
    path('detail_book/<int:pk>', views.DetailBook.as_view(), name='detail'),
] 

src/cart/urls.py
from django.urls import path
from cart.views import AddBookToCart, CartDelete, CartDetail
from . import views
app_name = 'cart'

urlpatterns = [
    path('add_to_cart/', views.AddBookToCart.as_view(), name='add'),
    path('delete_cart/<int:pk>', views.CartDelete.as_view(), name='delete'),
    path('detail_cart', views.CartDetail.as_view(), name='detail'),
] 

src/comments/urls.py
from django.urls import path
from comments.views import DeleteComment
app_name="comments"

urlpatterns = [
    path('delete/<int:pk>', DeleteComment.as_view(), name='delete'),
]

src/profiles/urls.py
from django.urls import path
from profiles.views import CreateProfile, UpdateProfile, DeleteProfile, DetailProfile, Login, LoginDone, Logout, PasswordChange, PasswordChangeDone
from . import views
app_name = 'profile'

urlpatterns = [
    path('update_profile/<int:pk>', UpdateProfile.as_view(), name='update'),
    path('delete_profile/<int:pk>', DeleteProfile.as_view(), name='delete'),
    path('detail_profile/<int:pk>', DetailProfile.as_view(), name='detail'),
    path('create_profile/', CreateProfile.as_view(), name='create'),
    path('login/', Login.as_view(), name='login'),
    path('login_done/', LoginDone.as_view(), name='login_done'),
    path('logout/', Logout.as_view(), name='logout'),
    path('password_change/', PasswordChange.as_view(), name='password_change'),
    path('password_change_done/', PasswordChangeDone.as_view(), name='password_change_done'),
] 

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import HomePageView, Search

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('genres/', include('genre.urls', namespace='genres')),
    path('books/', include('books.urls', namespace='books')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('author/', include('author.urls', namespace='author')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('publisher/', include('publisher.urls', namespace='publisher')),
    path('series/', include('series.urls', namespace='series')),
    path('', HomePageView.as_view(), name='home'),
    path('search/', Search.as_view(), name='search')
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/comments/models.py
from django.db import models
from books.models import Books
from order.models  import Order

class CommentsBook(models.Model):
    book = models.ForeignKey(
        Books, 
        verbose_name='Книга',
        on_delete=models.PROTECT,
        related_name='comments'
        )
    user = models.CharField(
        verbose_name='Имя',
        max_length=50
        )
    body = models.TextField(
        verbose_name='Комментарий'
    )
    created = models.DateTimeField(
        verbose_name='Дата добавления',
        auto_now=False,
        auto_now_add=True
    )
    updated = models.DateTimeField(
        verbose_name='Дата изменения',
        auto_now=True,
        auto_now_add=False
    )
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.body

# class CommentsOrder(models.Model):
#     order = models.ForeignKey(Order, related_name='comments', on_delete=models.PROTECT)
#     user = models.CharField(max_length=80)
#     body = models.TextField()
#     created = models.DateTimeField(auto_now_add=True)
#     updated = models.DateTimeField(auto_now=True)
#     active = models.BooleanField(default=True)

#     class Meta:
#         ordering = ('created',)

#     def __str__(self):
#         return 'Comment by {} on {}'.format(self.name, self.order)

src/comments/forms.py
from .models import CommentsBook
from django import forms

class CommentsForm(forms.ModelForm):
    class Meta:
        model = CommentsBook
        fields = ('user', 'body',)

src/comments/views.py
from django.shortcuts import render
from books.models import Books
from django.views.generic.edit import UpdateView
from .models import CommentsBook
from .forms import CommentsForm
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic.edit import DeleteView

class CreateComment(UpdateView):
    model = CommentsBook
    form_class = CommentsForm
    template_name='books/templates/books/detail_book.html'

    def get_object(self):
        book = get_object_or_404(Books, pk=self.kwargs.get('pk'))
        user = self.request.user
        obj, create = self.model.objects.get_or_create(
            book=book,
            user=user,
            body="Комментарий",
            )
        return obj

    def get_success_url(self):
       return reverse_lazy('home')

class DeleteComment(DeleteView):

    model = CommentsBook
    fields = ['body']
    template_name='comments/delete_comments.html'

    def get_success_url(self):
        book = self.object.book
        return reverse_lazy('books:detail', kwargs={'pk': book.pk})

src/templates/base.html
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title> {% block title %} Не сработало {% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  {% comment %} <link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> {% endcomment %}

    <style>
       body {
        background: #ebd5b3; /* Цвет фона */
        
      }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      footer {
        position: fixed;
        left: 7%; bottom: 0; /* Левый нижний угол */
        padding: 1px; /* Поля вокруг текста */
        background: rgb(52, 58, 68); /* Цвет фона */
        color: #fff; /* Цвет текста */
        width: 100%; /* Ширина слоя */
        margin-top: -50px; /*Минус Высота футера*/
        height: 50px; /*Высота футера*/
      }
    </style>

  </head>
  <body bgcolor="#fa8e47">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="{% url "home" %}">Книгарня</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href={% url "books:list" %}>Каталог книг<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Справочники</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="{% url "author:list" %}">Авторы</a>
          <a class="dropdown-item" href="{% url "genres:list" %}">Жанры</a>
          <a class="dropdown-item" href="{% url "publisher:list" %}">Издательства</a>
          <a class="dropdown-item" href="{% url "series:list" %}">Серии книг</a>
        </div>
      </li>
      {% if user.is_superuser %}:
       <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:login' %}">Админ</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="GET" value="{{ request.GET.q }}">
      <input class="form-control mr-sm-2" type="text" name='q' value="{{request.GET.q}}" placeholder="Поиск" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
    </form>
    &emsp;
      <div id="user-tools">
        {% if user.is_authenticated %}:
          <strong style="color:white;">Добро пожаловать, <a href="{% url "profile:detail" user.profile.pk %}">{{ user }}</a></strong>
          <a href="{% url "cart:detail" %}">Корзина</a>
          <a href="{% url "profile:logout" %}">Выйти</a>
        {% else %}:
          <button type="button" class="btn btn-light"><a href="{% url "profile:login" %}">Войти/Зарегистрироваться</a></button>
        {% endif %}
      </div>
  </div>
</nav>
<br><br><br>

<main role="main">
{% block body %}<h1>Не получилось</h1>{% endblock body %}
</main>
<br><br><br>

<footer class="container">
  <p>&copy; Книгарня 2020</p>
</footer>


      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

src/templates/base_login.html
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>Логин</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  {% comment %} <link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> {% endcomment %}

    <style>
      body {
        background: #ebd5b3; /* Цвет фона */
        
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      main {
        padding-bottom: 100px;
      }
      footer {
        position: fixed;
        left: 7%; bottom: 0; /* Левый нижний угол */
        padding: 1px; /* Поля вокруг текста */
        background: rgb(52, 58, 68); /* Цвет фона */
        color: #fff; /* Цвет текста */
        width: 100%; /* Ширина слоя */
        margin-top: -100px; /*Минус Высота футера*/
        height: 100px; /*Высота футера*/
      }
    </style>

  </head>
<body>
  
  <main role="main">
  {% block body %}<h1>Не получилось</h1>{% endblock body %}
  </main>
  <br><br><br>

  <footer class="container">
    <p>&copy; Книгарня 2020</p>
  </footer>


      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

src/templates/comments.html
{% load crispy_forms_tags %}
<br>
<div class='container'>

{% if request.user.is_authenticated %}
    <button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#exampleModal"> Написать комментарий <i class="fas fa-comment fa-2x" style="color:yellow" ></i></button>
{% endif %}
<br><br>

{% for comments in object.comments.all %}
    <li class="list-group-item list-group-item-secondary">
        <p><a href="{% url 'comments:delete' comments.pk %}"><button type="button" class="close"  aria-label="Close" ><span aria-hidden="true">&times;</span></button></a></p>
        <div class="date">{{ comments.created }}</div>
        <strong>{{ comments.user }}</strong>
        <p>{{ comments.body|linebreaks }}</p>
    </li>
{% empty %}
    <li class="list-group-item list-group-item-secondary">Комментариев пока не было. Ваш комментарий может быть первым <i class="far fa-smile"  ></i></li>
{% endfor %}
</div>
<br>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"> Комментарий к книге "{{object.name}}"</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-outline-warning" value="Подтвердить">      
        </form>
      </div>
    </div>
  </div>
</div>

src/templates/login.html
{% extends 'base_login.html' %}
{% load crispy_forms_tags %}

{% block title %}Логин{% endblock title %}

{% block body %}
  <div class='container'>
      <br><br><br>

{% if form.errors %}
<p>Ваши логин и пароль не совпадают. Попробуйте еще раз.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>У Вас нет доступа к этой странице.</p>
    {% else %}
    <p>Пожалуйста, войдите в учетную запись для продолжения.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'auth:login' %}">
{% csrf_token %}
      <div class="form-group">
        <label for="{{ object.username }}">Имя пользователя</label>
        <input type="username" class="form-control" id="{{ object.username }}" aria-describedby="Help">
        <small id="Help" class="form-text text-muted">Введите имя пользователя</small>
      </div>
      <div class="form-group">
        <label for="{{ object.password }}">Пароль</label>
        <input type="password" class="form-control" id="{{ object.password }}">
      </div>
      <button type="submit" class="btn btn-danger"><a href="{% url "profile:create" %}">Зарегистрироваться</a></button><br>
      <button type="submit" class="btn btn-primary">Войти</button>
    </form>

<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
{% comment %} <p><a href="{% url 'password_reset' %}">Lost password?</a></p> {% endcomment %}

{% endblock %}

src/templates/paginator.html
<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
        <a class="page-link" href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}" tabindex="-1" aria-disabled="true">Previous</a>
        </li>
        {% for page in page_obj.paginator.page_range %}
        
        <li class="page-item" {% if page_obj.number == page %}active{% endif %}><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>

        {% endfor %}

        <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
        <a class="page-link" href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}">Next</a>
        </li>
    </ul>
    </nav>  