src/books/urls.py
from django.urls import path
from books.views import CreateBook, UpdateBook, ListBook, DeleteBook, DetailBook, HomePageView
from . import views
app_name = 'books'

urlpatterns = [
    path('create_book/', views.CreateBook.as_view(), name='create'),
    path('update_book/<int:pk>', views.UpdateBook.as_view(), name='update'),
    path('list_book/', views.ListBook.as_view(), name='list'),
    path('delete_book/<int:pk>', views.DeleteBook.as_view(), name='delete'),
    path('detail_book/<int:pk>', views.DetailBook.as_view(), name='detail'),
] 

src/cart/urls.py
from django.urls import path
from cart.views import AddBookToCart, CartDelete, CartDetail
from . import views
app_name = 'cart'

urlpatterns = [
    path('add_to_cart/', views.AddBookToCart.as_view(), name='add'),
    path('delete_cart/<int:pk>', views.CartDelete.as_view(), name='delete'),
    path('detail_cart', views.CartDetail.as_view(), name='detail'),
] 

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import HomePageView, Search

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('genres/', include('genre.urls', namespace='genres')),
    path('books/', include('books.urls', namespace='books')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('author/', include('author.urls', namespace='author')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('publisher/', include('publisher.urls', namespace='publisher')),
    path('series/', include('series.urls', namespace='series')),
    path('', HomePageView.as_view(), name='home'),
    path('search/', Search.as_view(), name='search')
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/books/models.py
from django.db import models
from django.urls import reverse_lazy
from genre.models import Genre
from author.models import Author
from series.models import Series
from publisher.models import Publisher

class Books(models.Model):
    name = models.CharField(
        verbose_name='Название книги',
        max_length=100
    )
    author = models.ManyToManyField(
        Author,
        verbose_name='Автор',
        related_name='books'
    )
    series = models.ForeignKey(
        Series,
        verbose_name='Серия книг',
        related_name='series',
        on_delete=models.PROTECT
    )
    description = models.TextField(
        verbose_name='Описание книги',
        null=True,
        blank=True
    )
    genre = models.ManyToManyField(
        Genre,
        verbose_name='Жанр',
        related_name='books'
    )
    image = models.ImageField(
        verbose_name='Обложка книги',
        upload_to='book_cover',
        null=True,
        blank=False
    )
    price = models.FloatField(
        verbose_name='Стоимость книги',
    )
    year = models.IntegerField(
        verbose_name='Год издания',
    )
    quantity = models.IntegerField(
        verbose_name='Количество страниц',
    )
    binding = models.CharField(
        verbose_name='Переплет',
        max_length=100
    )
    forma = models.CharField(
        verbose_name='Формат',
        max_length=10
    )
    isbn = models.CharField(
        verbose_name='ISBN',
        max_length=20
    )
    weight = models.IntegerField(
        verbose_name='Вес (гр.)',
    )
    age = models.IntegerField(
        verbose_name='Возрастные ограничения',
    )
    publisher = models.ForeignKey(
        Publisher,
        verbose_name='Издательство',
        related_name='publisher',
        on_delete=models.PROTECT
    )
    rate = models.IntegerField(
        verbose_name='Рейтинг (0-10)',
    )
    add_time = models.DateTimeField(
        verbose_name='Дата добавления',
        auto_now=False,
        auto_now_add=True
    )
    update_time = models.DateTimeField(
        verbose_name='Дата изменения',
        auto_now=True,
        auto_now_add=False
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy("books:list")

src/books/forms.py
from django import forms
from .models import Books

class CreateBookForm(forms.ModelForm):
    class Meta:
        model = Books
        fields = (
            'name',
            'author',
            'description',
            'genre',
            'price',
            'image',
            'year',
            'quantity',
            'binding',
            'forma',
            'isbn',
            'weight',
            'age',
            'publisher',
            'rate',
        )

src/books/views.py
from .models import Books
from author.models import Author
from .forms import CreateBookForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.db.models import Q

from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView, TemplateView


# class HomePageView(ListView):
#     model = Books
#     template_name = 'books/home.html'
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['latest_books'] = Books.objects.reverse()[:5]
#         return context

class HomePageView(TemplateView):
    template_name = 'books/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_books'] = Books.objects.all().order_by('-add_time')[:6]
        context['most_popular'] = Books.objects.all().order_by('-rate')[:6]
        return context

class CreateBook(LoginRequiredMixin, CreateView):
    model = Books
    form_class = CreateBookForm
    template_name = 'books/create_book.html'


class UpdateBook(LoginRequiredMixin, UpdateView):
    model = Books
    form_class = CreateBookForm
    template_name = 'books/update_book.html'
    def get_success_url(self):
        return reverse_lazy('books:detail', kwargs={'pk': self.object.pk})
    

class ListBook(ListView):
    model = Books
    template_name = 'books/list_book.html'
    paginate_by = 10

class DeleteBook(LoginRequiredMixin, DeleteView):
    model = Books
    template_name = 'books/delete_book.html'
    success_url = reverse_lazy('books:list')

class DetailBook(DetailView):
    model = Books
    template_name = 'books/detail_book.html'

class Search(TemplateView):
    model = Books
    template_name = 'books/search.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q')

        results = Books.objects.filter(name__icontains=query)
        results1 = Author.objects.filter(name__icontains=query)

        context = {'results': results,
                'results1': results1}

        return context

src/books/templates/books/create_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Добавление книги{% endblock title %}

{% block body %}
  <div class='container'>
      <br><br>
      <h1>Добавить книгу</h1>
      <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" class="btn btn-outline-danger">Сохранить</button>
      </form>
  </div>  
{% endblock body %}

src/books/templates/books/delete_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Удаление книги{% endblock title %}

{% block body %}
    <div class='container'>
        <br><br>
        <h1>Удалить книгу {{ object.name }}</h1>
        <form action="" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger">Вы уверены?</button>
        </form>
    </div>  
{% endblock body %}

src/books/templates/books/detail_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Информация о книге{% endblock title %}

{% block body %}
  <style type="text/css">
   BODY {
    background: #ebd5b3; /* Цвет фона веб-страницы */
   }
   TABLE {
    width: 300px; /* Ширина таблицы */
    border-collapse: collapse; /* Убираем двойные линии между ячейками */
    border: 2px solid white; /* Прячем рамку вокруг таблицы */
   }
   TD, TH {
    padding: 3px; /* Поля вокруг содержимого таблицы */
    border: 1px solid maroon; /* Параметры рамки */
    text-align: left; /* Выравнивание по левому краю */
   }
  </style>
    <div class='container'>
        <br><br>
        <h1>Книга {{ object.name }}</h1>
        <div>
            <button data-cart-btn=""  class='container' class="ok-product__add-shcart ok-btn  -btn-shopping-cart ok-product__btn"><a class="ok-product__go-shcart ok-btn -btn-theme-action" href="{% url 'cart:add' %}?book_pk={{ object.pk }}"><span>В корзину</span></a></button>
        </div>
        <table width='100%' class='container' class="table table-bordered" cellspacing="0" border="2">
            <tr>
                <th scope="col">Обложка книги</th><td><img src="{{ object.image.url }}" width="150" alt=""> </td>
            </tr>
            <tr>
                <th scope="col">Автор книги</th><td>
                {% for author in object.author.all %}
                    <a href="{% url "author:detail" author.pk %}">{{ author }}</a>
                {% endfor %}
                </td>
            </tr>
            <tr>
                <th scope="col">Серия книг</th><td>
                {% for series in object.series.all %}
                    <a href="{% url "series:detail" series.pk %}">{{ series }}</a>
                {% endfor %}
                </td>
            </tr>
            <tr>
                <th scope="col">Описание книги</th><td>{{ object.description }}</td>
            </tr>
            <tr>
                <th scope="col">Жанр книги</th><td>
                {% for genre in object.genre.all %}
                    <a href="{% url "genres:detail" genre.pk %}">{{ genre }}</a><br>
                {% endfor %}
                </td>
            </tr>
            <tr>
                <th scope="col">Стоимость</th><td>{{ object.price }}</td>
            </tr>
            <tr>
                <th scope="col">Год издания</th><td>{{ object.year }}</td>
            </tr>
            <tr>
                <th scope="col">Количество страниц</th><td>{{ object.quantity }}</td>
            </tr>
            <tr>
                <th scope="col">Переплет</th><td>{{ object.binding }}</td>
            </tr>
            <tr>
                <th scope="col">Формат</th><td>{{ object.forma }}</td>
            </tr>
            <tr>
                <th scope="col">ISBN'</th><td>{{ object.isbn }}</td>
            </tr>
            <tr>
                <th scope="col">Вес (гр.)</th><td>{{ object.weight }}</td>
            </tr>
            <tr>
                <th scope="col">Возрастные ограничения</th><td>{{ object.age }}</td>
            </tr>
            <tr>
                <th scope="col">Издательство</th><td>
                {% for publisher in object.publisher.all %}
                    <a href="{% url "publisher:detail" publisher.pk %}">{{ publisher }}</a>
                {% endfor %}
                </td>
            </tr>
            <tr>
                <th scope="col">Рейтинг</th><td>{{ object.rate }}</td>
            </tr>
            <tr>
                <th scope="col">Дата добавления</th><td>{{ object.add_time }}</td>
            </tr>
            <tr>
                <th scope="col">Дата изменения</th><td>{{ object.update_time }}</td>
            </tr>
        </table>
    </div> 

    {% include "comments.html" %}

{% endblock body %}

src/books/templates/books/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Книгарня{% endblock title %}

{% block body %}
<br><br>

<div class="blog" >
 <div class="container" >
 <h1 class="text-center">Наши новинки</h1>
  <div class="row">
{% for obj in latest_books %}
   <div class="col-md-4 col-lg-4 col-sm-12">
    <div class="card">
     <div class="card-img">
      <a href="{% url "books:detail" obj.pk %}"><img src="{{ obj.image.url }}" width="150 class="card-img-fluid" alt=""></a>
     </div>
     <div class="card-body">
     <h5 class="card-title"><a href="{% url "books:detail" obj.pk %}">{{ obj.name }}</a></h5>
      <p class="card-text">
        Стоимость: {{ obj.price }}
      </p>
     </div>
     <div class="card-footer">
      <a href="{% url 'cart:add' %}?book_pk={{ obj.pk }}" class="card-link">В корзину</a>
     </div>
    </div>
   </div>
   {% if forloop.counter|divisibleby:3 %}
    </div>
    <div class="row">
    {% endif %}
   {% endfor %}
  </div>
 </div>
</div>

<br><br>

<div class="blog" >
 <div class="container" >
 <h1 class="text-center">Популярные</h1>
  <div class="row">
{% for obj in most_popular %}
   <div class="col-md-4 col-lg-4 col-sm-12">
    <div class="card">
     <div class="card-img">
      <a href="{% url "books:detail" obj.pk %}"><img src="{{ obj.image.url }}" width="150 class="card-img-fluid" alt=""></a>
     </div>
     <div class="card-body">
     <h5 class="card-title"><a href="{% url "books:detail" obj.pk %}">{{ obj.name }}</a></h5>
      <p class="card-text">
        Стоимость: {{ obj.price }}
      </p>
      <p class="card-text">
        Рейтинг: {{ obj.rate }}
      </p>
     </div>
     <div class="card-footer"> 
      <a href="{% url 'cart:add' %}?book_pk={{ obj.pk }}" class="card-link">В корзину</a>
     </div>
    </div>
   </div>
   {% if forloop.counter|divisibleby:3 %}
    </div>
    <div class="row">
    {% endif %}
   {% endfor %}
  </div>
 </div>
</div>

{% endblock body %}

src/books/templates/books/list_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}Список книг{% endblock title %}

{% block body %}
    <div class='container'>
    <br><br>
    <h1>Список книг</h1>
    {% if user.is_superuser %}:
        <a href="{% url 'books:create' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Добавить новую книгу</a><br>
    {% endif %}
    <br>
    {% include "paginator.html" %}
    
    <table width='100%' class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">Обложка</th>
                <th scope="col">Название книги</th>
                <th scope="col">Автор</th>
                <th scope="col">Жанр</th>
                <th scope="col">Стоимость</th>
                <th scope="col">Действие</th>            
            </tr>
        </thead>
        <tbody>
            <tr>
                {% for obj in object_list %}
                    <tr>
                        <td><img src="{{ obj.image.url }}" width="150" alt=""></td>
                        <td><a href="{% url "books:detail" obj.pk %}">{{ obj.name }}</a></td>
                        <td>
                        {% for author in obj.author.all %}
                            {{ author }}<br>
                        {% endfor %}
                        </td>
                        <td>
                        {% for genre in obj.genre.all %}
                            {{ genre }}<br>
                        {% endfor %}
                        </td>
                        <td>{{ obj.price }}</td>
                        <td>
                            {% if user.is_superuser %}:
                                <a href="{% url "books:update" obj.pk %}">Изменить</a><br>
                                <a href="{% url "books:delete" obj.pk %}">Удалить</a><br>
                            {% else %}
                                <a href="{% url 'cart:add' %}?book_pk={{ obj.pk }}">Добавить в корзину</a><br>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tr>
        </tbody>
    </table>
    </div> 
{% endblock body %}

src/books/templates/books/search.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Поиск {% endblock title %}

{% block body %}
<div class='container'>
    {% if results %}
        <h1>Результат поиска по <b>{{ request.GET.q }}</b></h1>
        <br/><br/>

        {% for result in results %}
            <h3><a href="{% url "books:detail" result.pk %}">{{ result.name }}</a></h3>
        {% endfor %}

    {% elif results1 %}
        <h1>Результат поиска по <b>{{ request.GET.q }}</b></h1>
        <br/><br/>

        {% for result in results1 %}
            <h3><a href="{% url "author:detail" result.pk %}">{{ result.name }}</a></h3>
        {% endfor %}

    {% else %}
        По результатам поиска ничего не найдено
    {% endif %}
</div>
{% endblock body %}

src/books/templates/books/update_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Изменение книги{% endblock title %}

{% block body %}
    <div class='container'>
    <br><br>
    <h1>Изменить книгу</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Подтвердить">
    </form>
    </div> 
{% endblock body %}