src/cart/urls.py
from django.urls import path
from cart.views import AddBookToCart, CartDelete, CartDetail
from . import views
app_name = 'cart'

urlpatterns = [
    path('add_to_cart/', views.AddBookToCart.as_view(), name='add'),
    path('delete_cart/<int:pk>', views.CartDelete.as_view(), name='delete'),
    path('detail_cart', views.CartDetail.as_view(), name='detail'),
] 

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import HomePageView, Search

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('genres/', include('genre.urls', namespace='genres')),
    path('books/', include('books.urls', namespace='books')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('author/', include('author.urls', namespace='author')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('publisher/', include('publisher.urls', namespace='publisher')),
    path('series/', include('series.urls', namespace='series')),
    path('', HomePageView.as_view(), name='home'),
    path('search/', Search.as_view(), name='search')
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/series/urls.py
from django.urls import path
from series.views import CreateSeries, UpdateSeries, ListSeries, DeleteSeries, DetailSeries
from . import views
app_name = 'series'

urlpatterns = [
    path('create_series/', views.CreateSeries.as_view(), name='create'),
    path('update_series/<int:pk>', views.UpdateSeries.as_view(), name='update'),
    path('list_series/', views.ListSeries.as_view(), name='list'),
    path('delete_series/<int:pk>', views.DeleteSeries.as_view(), name='delete'),
    path('detail/<int:pk>', views.DetailSeries.as_view(), name='detail'),
] 

src/series/models.py
from django.db import models


class Series(models.Model):
    name = models.CharField(
        verbose_name="Название серии",
        max_length=50,
        null=True,
        blank=False,
    )
    description = models.TextField(
        verbose_name="Описание серии",
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy("series:list")

src/series/views.py
from .models import Series
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count

from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView

class CreateSeries(LoginRequiredMixin, CreateView):
    model = Series
    fields = ('name','description')
    template_name = 'series/create_series.html'
    success_url = reverse_lazy('series:list')

class UpdateSeries(LoginRequiredMixin, UpdateView):
    model = Series
    fields = ('name','description')
    template_name = 'series/update_series.html'
    success_url = reverse_lazy('series:list')
    
class ListSeries(ListView):
    model = Series
    template_name = 'series/list_series.html'

class DeleteSeries(LoginRequiredMixin, DeleteView):
    model = Series
    template_name = 'series/delete_series.html'
    success_url = reverse_lazy('series:list')

class DetailSeries(DetailView):
    model = Series
    template_name = 'series/detail_series.html'

src/series/templates/series/create_series.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Создание серии{% endblock title %}

{% block body %}
  <div class='container'>
      <br><br>
      <h1>Добавить серию книг</h1>
      <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" class="btn btn-outline-danger">Сохранить</button>
      </form>
  </div>  
{% endblock body %}

src/series/templates/series/delete_series.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Удаление серии книг{% endblock title %}

{% block body %}
    <div class='container'>
        <br><br>
        <h1>Удалить серию книг {{ object.name }}</h1>
        <form action="" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger">Вы уверены?</button>
        </form>
    </div>  
{% endblock body %}

src/series/templates/series/detail_series.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Информация о серии книг{% endblock title %}

{% block body %}
    <div class='container'>
        <br><br>
        <h1>{{ object.name }}</h1>
        <table width='100%' class="table table-bordered">
            <tr>
                <th scope="col">Название серии</th><td>{{ object.name }}</td>
            </tr>
            <tr>
                <th scope="col">Описание серии</th><td>{{ object.description }}</td>
            </tr>
            <tr>
                <th scope="col">Книги в серии</th>
                <td>
                    {% for book in object.books.all %}
                        <a href="{% url "books:detail" book.pk %}">{{ book }}</a><br>
                    {% endfor %}
                </td>
            </tr>
        </table>
    </div>  
{% endblock body %}

src/series/templates/series/list_series.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}Список серий книг{% endblock title %}

{% block body %}
    <div class='container'>
    <br><br>
    <h1>Список серий книг</h1>
    {% if user.is_superuser %}:
        <a href="{% url 'series:create' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Добавить серию книг</a><br>
    {% endif %}
    <table width='100%' class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">Название</th> 
                <th scope="col">Описание</th>             
            </tr>
        </thead>
        <tbody>
            <tr>
                {% for obj in object_list %}
                    <tr>
                        <td><a href="{% url "series:detail" obj.pk %}">{{ obj.name }}</a></td>
                        <td>{{ obj.description }}</td>
                        <td>
                            {% if user.is_superuser %}:
                                <a href="{% url "series:update" obj.pk %}">Изменить</a><br>
                                <a href="{% url "series:delete" obj.pk %}">Удалить</a><br>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tr>
        </tbody>
    </table>
    </div> 
{% endblock body %}

src/series/templates/series/update_series.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Изменение данных серии книг{% endblock title %}

{% block body %}
    <div class='container'>
    <br><br>
    <h1>Изменить данные серии книг</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-outline-danger" value="Подтвердить">
    </form>
    </div> 
{% endblock body %}